///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TodoModel {
/*
{
  "title": "67ac3f12b2a7e4632213f9b1",
  "description": "Guided Sessions",
  "status": false
} 
*/

  String? title;
  String? description;
  bool? status;

  TodoModel({
    this.title,
    this.description,
    this.status,
  });
  TodoModel.fromJson(Map<String, dynamic> json) {
    title = json['title'] ?? "";
    description = json['description'] ?? "";
    status = json['status'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['description'] = description;
    data['status'] = status;
    return data;
  }
}
